import {UseragentBot} from "./bot/useragent-bot";

export type UseragentBrowser = UseragentBot |
	"Amaya"
	| "Android Browser"
	| "Arora"
	| "Avant"
	| "Baidu"
	| "Blazer"
	| "Bolt"
	| "Camino"
	| "Chimera"
	| "Chrome"
	| "Chromium"
	| "Chrome Headless"
	| "Comodo Dragon"
	| "Conkeror"
	| "Dillo"
	| "Dolphin"
	| "Doris"
	| "Edge"
	| "Epiphany"
	| "Fennec"
	| "Firebird"
	| "Firefox"
	| "Flock"
	| "GoBrowser"
	| "iCab"
	| "ICE Browser"
	| "IceApe"
	| "IceCat"
	| "IceDragon"
	| "Iceweasel"
	| "IE"
	| "IE Mobile"
	| "IEMobile"
	| "Iron"
	| "Jasmine"
	| "K-Meleon"
	| "Konqueror"
	| "Kindle"
	| "Links"
	| "Lunascape"
	| "Lynx"
	| "Maemo"
	| "Maxthon"
	| "Midori"
	| "Minimo"
	| "MIUI Browser"
	| "Safari"
	| "Mobile Safari"
	| "MobileSafari"
	| "SafariMobile"
	| "Safari Mobile"
	| "Mosaic"
	| "Mozilla"
	| "Netfront"
	| "Netscape"
	| "NetSurf"
	| "Nokia"
	| "OmniWeb"
	| "Opera"
	| "Opera Mini"
	| "Opera Mobi"
	| "Opera Tablet"
	| "Phoenix"
	| "Polaris"
	| "QQBrowser"
	| "RockMelt"
	| "Silk"
	| "Skyfire"
	| "SeaMonkey"
	| "SlimBrowser"
	| "Swiftfox"
	| "Tizen"
	| "UCBrowser"
	| "Vivaldi"
	| "w3m"
	| "WebKit"
	| "Yandex";